include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    deprecated_member_use: ignore
    avoid_redundant_argument_values: ignore
    join_return_with_assignment: ignore
